name: PAM
channels:
- conda-forge
- defaults
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
dependencies:
- libstdcxx=14.2.0
- libstdcxx-ng=14.2.0
- libuuid=1.41.5
- mpi=1.0
- mpi4py=3.1.6
- ncurses=6.4
- openmpi=4.1.6
- openssl=3.5.0
- pip=25.0
- python=3.10.16
- readline=8.2
- setuptools=75.8.0
- sqlite=3.45.3
- tk=8.6.14
- wheel=0.45.1
- xz=5.6.4
- zlib=1.2.13
- pip:
  - accelerate==1.4.0
  - addict==2.4.0
  - aitviewer==1.13.0
  - annotated-types==0.7.0
  - anyio==4.9.0
  - asttokens==3.0.0
  - async-timeout==5.0.1
  - attrs==25.3.0
  - basicsr==1.4.1
  - beautifulsoup4==4.13.4
  - bitsandbytes==0.45.3
  - black==25.1.0
  - blessed==1.21.0
  - blinker==1.9.0
  - botorch==0.1.4
  - bottleneck==1.5.0
  - braceexpand==0.1.7
  - certifi==2025.1.31
  - charset-normalizer==3.4.1
  - chumpy==0.71
  - click==8.1.8
  - cloudpickle==3.1.1
  - coloredlogs==15.0.1
  - colorlog==6.9.0
  - comm==0.2.3
  - conda-pack==0.8.1
  - configargparse==1.7.1
  - contourpy==1.3.1
  - cupy-cuda11x==13.4.0
  - cupy-cuda12x==13.4.1
  - cycler==0.12.1
  - cython==3.0.12
  - dash==3.2.0
  - datasets==3.4.1
  - decorator==5.2.1
  - decord==0.6.0
  - deepspeed==0.16.4
  - detectron2==0.6+2a420edpt2.4.1cu121
  - diffusers==0.32.2
  - dill==0.3.8
  - distro==1.9.0
  - docker-pycreds==0.4.0
  - easydict==1.13
  - einops==0.8.0
  - exceptiongroup==1.2.2
  - executing==2.2.1
  - faiss-gpu==1.7.2
  - fastai==1.0.61
  - fastjsonschema==2.21.2
  - fastprogress==1.0.3
  - fastrlock==0.8.3
  - filelock==3.18.0
  - fire==0.7.1
  - flask==3.1.2
  - flatbuffers==25.2.10
  - flow-vis==0.1
  - fonttools==4.56.0
  - freetype-py==2.5.1
  - frozenlist==1.5.0
  - fsspec==2024.12.0
  - future==1.0.0
  - fvcore==0.1.5.post20221221
  - gdown==5.2.0
  - geffnet==1.0.2
  - gitdb==4.0.12
  - gitpython==3.1.44
  - glcontext==3.0.0
  - gpustat==1.1.1
  - gpytorch==1.8.0
  - grpcio==1.71.0
  - h11==0.14.0
  - hf-transfer==0.1.9
  - hjson==3.1.0
  - httpcore==1.0.7
  - httpx==0.28.1
  - huggingface-hub==0.29.3
  - humanfriendly==10.0
  - hydra-colorlog==1.2.0
  - hydra-core==1.3.2
  - hydra-submitit-launcher==1.2.0
  - idna==3.10
  - image-gen-aux==0.1.0.dev0
  - imageio==2.37.0
  - imageio-ffmpeg==0.6.0
  - imgui==2.0.0
  - importlib-metadata==8.6.1
  - iopath==0.1.9
  - ipython==8.37.0
  - ipywidgets==8.1.7
  - itsdangerous==2.2.0
  - jaxtyping==0.3.1
  - jedi==0.19.2
  - jinja2==3.1.6
  - jiter==0.9.0
  - joblib==1.4.2
  - json-tricks==3.17.3
  - jsonpatch==1.33
  - jsonpointer==3.0.0
  - jsonschema==4.25.1
  - jsonschema-specifications==2025.4.1
  - jupyter-core==5.8.1
  - jupyterlab-widgets==3.0.15
  - kiwisolver==1.4.8
  - kornia==0.8.0
  - kornia-rs==0.1.8
  - lazy-loader==0.4
  - lightning-utilities==0.14.3
  - linear-operator==0.6
  - lmdb==1.6.2
  - loguru==0.7.3
  - manopth==0.0.1
  - markdown==3.8
  - markdown-it-py==3.0.0
  - markupsafe==3.0.2
  - matplotlib==3.10.1
  - matplotlib-inline==0.1.7
  - mdurl==0.1.2
  - mediapy==1.2.4
  - memory-profiler==0.61.0
  - mmcv==1.3.9
  - mmengine==0.10.7
  - moderngl==5.12.0
  - moderngl-window==2.4.6
  - moviepy==1.0.3
  - mpmath==1.3.0
  - msgpack==1.1.0
  - multidict==6.2.0
  - multipledispatch==1.0.0
  - multiprocess==0.70.16
  - munkres==1.1.4
  - mypy-extensions==1.1.0
  - narwhals==2.3.0
  - nbformat==5.10.4
  - nest-asyncio==1.6.0
  - networkx==3.4.2
  - ninja==1.11.1.4
  - numexpr==2.10.2
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.1.3.1
  - nvidia-cuda-cupti-cu12==12.1.105
  - nvidia-cuda-nvrtc-cu12==12.1.105
  - nvidia-cuda-runtime-cu12==12.1.105
  - nvidia-cudnn-cu12==9.1.0.70
  - nvidia-cufft-cu12==11.0.2.54
  - nvidia-curand-cu12==10.3.2.106
  - nvidia-cusolver-cu12==11.4.5.107
  - nvidia-cusparse-cu12==12.1.0.106
  - nvidia-cusparselt-cu12==0.6.2
  - nvidia-ml-py==12.575.51
  - nvidia-ml-py3==7.352.0
  - nvidia-nccl-cu12==2.21.5
  - nvidia-nvjitlink-cu12==12.4.99
  - nvidia-nvtx-cu12==12.1.105
  - nvitop==1.5.3
  - omegaconf==2.3.0
  - onnxruntime==1.21.0
  - open3d==0.19.0
  - openai==1.69.0
  - opencv-contrib-python-headless==4.11.0.86
  - opencv-python==4.11.0.86
  - opencv-python-headless==4.11.0.86
  - optimum-quanto==0.2.6
  - packaging==24.2
  - pandas==2.2.3
  - parso==0.8.5
  - pathspec==0.12.1
  - peft==0.14.0
  - pexpect==4.9.0
  - pillow==11.1.0
  - platformdirs==4.3.7
  - plotly==6.3.0
  - pooch==1.8.2
  - portalocker==3.1.1
  - proglog==0.1.10
  - prompt-toolkit==3.0.52
  - propcache==0.3.1
  - protobuf==5.29.4
  - psutil==7.0.0
  - ptyprocess==0.7.0
  - pure-eval==0.2.3
  - py-cpuinfo==9.0.0
  - pyarrow==19.0.1
  - pycocotools==2.0.8
  - pydantic==2.10.6
  - pydantic-core==2.27.2
  - pyglet==2.1.6
  - pyglm==2.8.2
  - pygments==2.19.1
  - pyopengl==3.1.0
  - pyparsing==3.2.3
  - pyqt5==5.15.11
  - pyqt5-qt5==5.15.17
  - pyqt5-sip==12.17.0
  - pyqtwebengine==5.15.7
  - pyqtwebengine-qt5==5.15.17
  - pyquaternion==0.9.9
  - pyrender==0.1.45
  - pyrootutils==1.0.4
  - pyrr==0.10.3
  - pysocks==1.7.1
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.1.0
  - python-fcl==0.7.0.8
  - pytorch-fid==0.3.0
  - pytorch-lightning==2.5.1.post0
  - pytz==2025.2
  - pyvirtualdisplay==3.0
  - pyvista==0.46.3
  - pyyaml==6.0.2
  - referencing==0.36.2
  - regex==2024.11.6
  - requests==2.32.3
  - retrying==1.4.2
  - rich==14.0.0
  - roma==1.5.4
  - rpds-py==0.27.1
  - ruamel-yaml==0.18.15
  - ruamel-yaml-clib==0.2.12
  - safetensors==0.5.3
  - scikit-image==0.25.2
  - scikit-learn==1.6.1
  - scikit-video==1.1.11
  - scipy==1.15.2
  - scooby==0.10.1
  - sentencepiece==0.2.0
  - sentry-sdk==2.24.1
  - setproctitle==1.3.5
  - six==1.17.0
  - smmap==5.0.2
  - smplx==0.1.28
  - sniffio==1.3.1
  - soupsieve==2.7
  - spandrel==0.4.1
  - stack-data==0.6.3
  - submitit==1.5.2
  - sympy==1.13.1
  - tabulate==0.9.0
  - tb-nightly==2.20.0a20250531
  - tensorboard==2.19.0
  - tensorboard-data-server==0.7.2
  - termcolor==3.1.0
  - threadpoolctl==3.6.0
  - tifffile==2025.3.30
  - timm==1.0.15
  - tokenizers==0.21.0
  - tomli==2.2.1
  - torch==2.5.1+cu121
  - torch-scatter==2.1.2+pt21cu121
  - torch-sparse==0.6.18+pt21cu121
  - torchao==0.9.0
  - torchaudio==2.5.1+cu121
  - torchmetrics==1.7.1
  - torchvision==0.20.1+cu121
  - tornado==6.5.1
  - tqdm==4.67.1
  - traitlets==5.14.3
  - transformers==4.49.0
  - trimesh==4.6.4
  - triton==3.1.0
  - typing-extensions==4.13.0
  - tzdata==2025.2
  - urllib3==2.3.0
  - usd-core==25.8
  - visdom==0.2.4
  - vtk==9.5.1
  - wadler-lindig==0.1.4
  - wandb==0.19.8
  - wcwidth==0.2.13
  - webdataset==0.2.111
  - websocket-client==1.8.0
  - websockets==15.0.1
  - werkzeug==3.1.3
  - widgetsnbextension==4.0.14
  - xformers==0.0.29.post1
  - xtcocotools==1.14.3
  - xvfbwrapper==0.2.13
  - xxhash==3.5.0
  - yacs==0.1.8
  - yapf==0.43.0
  - yarl==1.18.3
  - yt-dlp==2025.2.19
  - zipp==3.21.0
